version: "^2.4.0 || @head"
export: |

    function buildSFML(lib)

        kind "StaticLib" 
        includedirs "src"

        files {
            ("include/SFML/%s/*.inl"):format(lib),
            ("src/SFML/%s/*.cpp"):format(lib)
        }

        filter "system:windows"
            files {
                ("src/SFML/%s/Win32/*.cpp"):format(lib)
            }

        filter "system:linux"
            files {
                ("src/SFML/%s/Unix/*.cpp"):format(lib)
            }

        filter "system:macosx"
            files {
                ("src/SFML/%s/OSX/*.cpp"):format(lib),
                ("src/SFML/%s/OSX/*.mm"):format(lib),
                ("src/SFML/%s/OSX/*.m"):format(lib)
            }
        
        filter "action:android"
            files {
                ("src/SFML/%s/Android/*.cpp"):format(lib)
            }

        filter "system:macosx"
            linkoptions "-ObjC -framework CoreFoundation -framework AppKit -framework IOKit -framework Carbon -framework OpenGL"

        filter {}

        zpm.export(function()
        
            defines "SFML_STATIC"

            includedirs "include"
    
        end)
    end

    project "SFML-system"

        buildSFML("System")
        
        filter "system:macosx"
            files {
                "src/SFML/System/Unix/*.cpp"
            }
        
        filter {}


    project "SFML-window"

        buildSFML("Window")
    
        links "SFML-system"

        filter "system:*"

            removefiles {
                "src/SFML/Window/EGLCheck.cpp",
                "src/SFML/Window/EglContext.cpp"
            }
        
        filter "system:macosx"
            includedirs "/opt/X11/include"

        filter "system:windows"
        
            links { 
                "OpenGL32", 
                "Winmm",
                "gdi32"
            }

        filter {} 

    project "SFML-graphics"

        buildSFML("Graphics")

        includedirs {
            "extlibs/headers/stb_image",
            "extlibs/headers/freetype2" 
        }
    
        links { 
            "SFML-system",
            "SFML-window" 
        }

        filter "system:windows"
        
            links { 
                "OpenGL32", 
                "Winmm" 
            }

        filter {}