sudo: required
language: generic
matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          dist: trusty          
          env: VERSION=6
        - os: linux
          dist: trusty          
          env: VERSION=5
        # Use generic language for osx
        - os: osx
          osx_image: xcode8
          language: generic

install:
    - bash script/install-unix.sh
    - wget -O - https://raw.githubusercontent.com/Zefiros-Software/ZPM/master/script/install-zpm-travis.sh | bash
script:
    - bash script/travis-build.sh
notifications:
    slack:
        secure: "G3W9MMAAY9U96tqhCUcPHdmLNtATFZsIKWGey/1AazExb50k1E4K1q7FVV7f/5SkOU27VjRM8jGtHyQBcZFpYn8nWQbQp8YaEq78uRz23Wsyvfh6damtJ9k7mH4cP/8QHTOAs6sbU/4khYqRDWQBysiB+Y+62m3h0uVlBAksiKTxed/qVffetwWN3Dxl7VW1ZdoaiaMpoUzifFaxgLNZKQ8zeExQRpVn6gauKPOUJDJDANk+1xA6lMKkRjFNPhVaZgo1tH1293UCxqGOwRYiuW7u7A8Z59Mpwj9JmeCukBJ3R4+l0/5jU8+0gZIkp9oB46xVpb25bGFnO2YV/CEAilLOm2tkzw8MP+4V8+XrlqL1JX9o2O/uW/FnFK/fGqtCY90AwVpeQqhLMODwQW6KRxby3MbILPj2SGZCOACimexcKzs+/JjCUFnw/3d44oTofaZcmcd49VWpsQwfiUSXLi4fqJbYINEKbLabABrlsVafH2lPNW4qee0RwXLZ+nLMDOkBVBa8e4skWxnIMARIzTOB8uG+GH0IRpbd61kvh6y8RoSwV4hebqLgQXuUoH1oUs6g6IAiHg9liFr8HRZapKx/YQoT83esRkQnr2U8Flb+XXX37lnyTcWHMxDqdzqCUnbGWaEl6AC+JqnLrvPrgMjwyWIFJiFUAjEWKQnh4Fs="